# Generated by Django 5.0.4 on 2024-05-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_remove_problem_curators_remove_problem_testers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='group',
        ),
        migrations.DeleteModel(
            name='ProblemClass',
        ),
        migrations.DeleteModel(
            name='ProblemGroup',
        ),
    ]
